id,name,raw,category,processed,solution,target,version
5917,44,"2023-04-14 05:42:28,014 | Failed at Play [27_sata_vhba_device_ops] *******************
2023-04-14 05:42:28,014 | TASK [27_sata_vhba_device_ops][Check new disk is recognized by guest OS] 
task path: /home/worker/workspace/Ansible_Cycle_SLED_15.x/ansible-vsphere-gos-validation/linux/vhba_hot_add_remove/hot_add_remove_disk.yml:39
fatal: [localhost]: FAILED! => Guest OS failed to recognize the new hot-added sata disk
error message:
Guest OS failed to recognize the new hot-added sata disk",,timestamp failed at play number sata v hba device ops timestamp task number sata v hba device ops check new disk is recognized by guest os task path home worker workspace ansible cycle sled number x ansible vsphere gos validation linux v hba hot add remove hot add remove disk yml number fatal localhost failed guest os failed to recognize the new hot added sata disk error message guest os failed to recognize the new hot added sata disk,deepdive,product,202304191023
5918,45,"2023-04-17 10:47:51,017 | Failed at Play [1_sata_vhba_device_ops] ********************
2023-04-17 10:47:51,017 | TASK [1_sata_vhba_device_ops][Check new disk is recognized by guest OS] 
task path: /home/worker/workspace/Ansible_Cycle_SLED_15.x/ansible-vsphere-gos-validation/linux/vhba_hot_add_remove/hot_add_remove_disk.yml:39
fatal: [localhost]: FAILED! => Guest OS failed to recognize the new hot-added sata disk
error message:
Guest OS failed to recognize the new hot-added sata disk",,timestamp failed at play number sata v hba device ops timestamp task number sata v hba device ops check new disk is recognized by guest os task path home worker workspace ansible cycle sled number x ansible vsphere gos validation linux v hba hot add remove hot add remove disk yml number fatal localhost failed guest os failed to recognize the new hot added sata disk error message guest os failed to recognize the new hot added sata disk,deepdive,product,202304191023
5919,45,"2023-04-17 08:33:08,017 | Failed at Play [1_deploy_vm] *******************************
2023-04-17 08:33:08,017 | TASK [1_deploy_vm][Get VM's network adapter] ***************
task path: /home/worker/workspace/Ansible_Ubuntu_23.04_Desktop_ISO_MAIN_SATA_VMXNET3_EFI/ansible-vsphere-gos-validation/linux/deploy_vm/deploy_vm_from_iso.yml:193
fatal: [localhost]: FAILED! => Could not find or access '/home/worker/workspace/Ansible_Ubuntu_23.04_Desktop_ISO_MAIN_SATA_VMXNET3_EFI/ansible-vsphere-gos-validation/linux/deploy_vm/vm_get_network_facts.yml' on the Ansible Controller.
error message:
2023-04-17 08:33:17,017 | TASK [1_deploy_vm][Testing exit due to failure] ************
task path: /home/worker/workspace/Ansible_Ubuntu_23.04_Desktop_ISO_MAIN_SATA_VMXNET3_EFI/ansible-vsphere-gos-validation/common/test_rescue.yml:87
fatal: [localhost]: FAILED! => Exit testing because 'exit_testing_when_fail' is set to True in test case deploy_vm_efi_sata_vmxnet3
error message:
Exit testing because 'exit_testing_when_fail' is set to True in test case deploy_vm_efi_sata_vmxnet3",,timestamp failed at play number deploy vm timestamp task number deploy vm get vm s network adapter task path home worker workspace ansible ubuntu number desktop iso main sata vmxnet number efi ansible vsphere gos validation linux deploy vm deploy vm from iso yml number fatal localhost failed could not find or access home worker workspace ansible ubuntu number desktop iso main sata vmxnet number efi ansible vsphere gos validation linux deploy vm vm get network facts yml on the ansible controller error message timestamp task number deploy vm testing exit due to failure task path home worker workspace ansible ubuntu number desktop iso main sata vmxnet number efi ansible vsphere gos validation common test rescue yml number fatal localhost failed exit testing because exit testing when fail is set to true in test case deploy vm efi sata vmxnet number error message exit testing because exit testing when fail is set to true in test case deploy vm efi sata vmxnet number,deepdive,testcase,202304191023
5920,45,"2023-04-15 16:24:02,015 | Failed at Play [19_pvrdma_network_device_ops] **************
2023-04-15 16:24:02,015 | TASK [19_pvrdma_network_device_ops][Check RDMA ping result from client VM to server VM] 
task path: /home/worker/workspace/Ansible_SLES_15SP4_70GA_LSILOGICSAS_VMXNET3_EFI/ansible-vsphere-gos-validation/linux/network_device_ops/pvrdma_network_device_ops.yml:161
fatal: [localhost]: FAILED! => Failed to run RDMA ping from client VM 'test_vm_client_20230415161808' to server VM 'test_vm'. Hit error 'cma event RDMA_CM_EVENT_REJECTED, error 8'
error message:
Failed to run RDMA ping from client VM 'test_vm_client_20230415161808' to server VM 'test_vm'. Hit error 'cma event RDMA_CM_EVENT_REJECTED, error 8'",,timestamp failed at play number pvrdma network device ops timestamp task number pvrdma network device ops check remote direct memory access ping result from client vm to server vm task path home worker workspace ansible sles number ga lsi logic sas vmxnet number efi ansible vsphere gos validation linux network device ops pvrdma network device ops yml number fatal localhost failed failed to run remote direct memory access ping from client vm test vm client timestamp to server vm test vm hit error cma event remote direct memory access cm event rejected error number error message failed to run remote direct memory access ping from client vm test vm client timestamp to server vm test vm hit error cma event remote direct memory access cm event rejected error number,retry,targetvm,202304191023
5921,45,"2023-04-19 03:14:27,019 | Failed at Play [1_deploy_vm] *******************************
2023-04-19 03:14:27,019 | TASK [1_deploy_vm][Check VM's primary network adapter have mac address] 
task path: /home/worker/workspace/Ansible_Debian_11.x_64bit_MAIN_PARAVIRTUAL_VMXNET3_EFI_HW17/ansible-vsphere-gos-validation/common/vm_wait_primary_nic_mac.yml:27
fatal: [localhost]: FAILED! => It's timed out to wait for VM's primary network adapter having MAC address in 10 minutes. Current VM's network facts is {'network_info': [{'mac_address': None, 'label': 'Network adapter 1', 'unit_number': 7, 'wake_onlan': True, 'allow_guest_ctl': True, 'connected': False, 'start_connected': True, 'network_name': 'VM Network', 'vlan_id': 0, 'switch': 'vSwitch0', 'device_type': 'vmxnet3', 'mac_addr': None, 'name': 'VM Network'}], 'network_data': {'0': {'mac_address': None, 'label': 'Network adapter 1', 'unit_number': 7, 'wake_onlan': True, 'allow_guest_ctl': True, 'connected': False, 'start_connected': True, 'network_name': 'VM Network', 'vlan_id': 0, 'switch': 'vSwitch0', 'device_type': 'vmxnet3', 'mac_addr': None, 'name': 'VM Network'}}, 'changed': False, 'failed': True, 'attempts': 120}.
error message:
It's timed out to wait for VM's primary network adapter having MAC address in 10 minutes. Current VM's network facts is {'network_info': [{'mac_address': None, 'label': 'Network adapter 1', 'unit_number': 7, 'wake_onlan': True, 'allow_guest_ctl': True, 'connected': False, 'start_connected': True, 'network_name': 'VM Network', 'vlan_id': 0, 'switch': 'vSwitch0', 'device_type': 'vmxnet3', 'mac_addr': None, 'name': 'VM Network'}], 'network_data': {'0': {'mac_address': None, 'label': 'Network adapter 1', 'unit_number': 7, 'wake_onlan': True, 'allow_guest_ctl': True, 'connected': False, 'start_connected': True, 'network_name': 'VM Network', 'vlan_id': 0, 'switch': 'vSwitch0', 'device_type': 'vmxnet3', 'mac_addr': None, 'name': 'VM Network'}}, 'changed': False, 'failed': True, 'attempts': 120}.
2023-04-19 03:14:29,019 | TASK [1_deploy_vm][Testing exit due to failure] ************
task path: /home/worker/workspace/Ansible_Debian_11.x_64bit_MAIN_PARAVIRTUAL_VMXNET3_EFI_HW17/ansible-vsphere-gos-validation/common/test_rescue.yml:87
fatal: [localhost]: FAILED! => Exit testing because 'exit_testing_when_fail' is set to True in test case deploy_vm_efi_paravirtual_vmxnet3
error message:
Exit testing because 'exit_testing_when_fail' is set to True in test case deploy_vm_efi_paravirtual_vmxnet3",,timestamp failed at play number deploy vm timestamp task number deploy vm check vm s primary network adapter have mac address task path home worker workspace ansible debian number x number b it main para virtual vmxnet number efi ansible vsphere gos validation common vm wait primary nic mac yml number fatal localhost failed it s timed out to wait for vm s primary network adapter having mac address in number minutes current vm s network facts is network info mac address none label network adapter number unit number wake on lan true allow guest ctl true connected false start connected true network name vm network vlan id number switch vswitch number device type vmxnet number mac address none name vm network network data number mac address none label network adapter number unit number wake on lan true allow guest ctl true connected false start connected true network name vm network vlan id number switch vswitch number device type vmxnet number mac address none name vm network changed false failed true attempts number error message it s timed out to wait for vm s primary network adapter having mac address in number minutes current vm s network facts is network info mac address none label network adapter number unit number wake on lan true allow guest ctl true connected false start connected true network name vm network vlan id number switch vswitch number device type vmxnet number mac address none name vm network network data number mac address none label network adapter number unit number wake on lan true allow guest ctl true connected false start connected true network name vm network vlan id number switch vswitch number device type vmxnet number mac address none name vm network changed false failed true attempts number timestamp task number deploy vm testing exit due to failure task path home worker workspace ansible debian number x number b it main para virtual vmxnet number efi ansible vsphere gos validation common test rescue yml number fatal localhost failed exit testing because exit testing when fail is set to true in test case deploy vm efi para virtual vmxnet number error message exit testing because exit testing when fail is set to true in test case deploy vm efi para virtual vmxnet number,deepdive,targetvm,202304191023
